### ISSUE TITLE
unsubscribe should show subscription help

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#104]

**Comment by endrawes0** [comment]
if I recall - seems to me you wanted to add another handler to show help because unsubscribe may be the natural way to remove a subscription, but it is not the command we went with...

I could be wrong.

Seems it could be just as simple to add the unsubscribe command

`unsubscribe <id>`
vs
`subscription remove <id>`

**Comment by lakinwecker** [comment]
Aah, yes. That's correct. Thanks.

**Comment by endrawes0** [comment]
welcome
