### ISSUE TITLE
Show each user timezone name, instead of only "in your timezone", to avoid problems in DST transitions

### ISSUE THREAD

**Issue by kuc** [endrawes0/Chesster#187]
User's current timezone name is in field `tz_label`:
https://api.slack.com/methods/users.list

**Comment by endrawes0** [comment]
Good idea

**Comment by lakinwecker** [comment]
Agreed, great idea!

Also, we can use `tz` to calculate future times, rather than offset. I suspect this will fix most DST issues.

**Comment by lakinwecker** [comment]
https://github.com/endrawes0/Chesster/pull/188 this pull request uses the .tz attribute to properly take into account DST.

tz_label suffers from the same problem as tz_offset. Unfortunately, it says things like "Mountain Daylight Time" instead of "Mountain Time". But DST switching occurs, you switch between "Mountain Daylight Time" and "Mountain Standard Time", which means that the label is in correct when there is a DST transition between now and when the game is scheduled.  However, the .tz label uses the Timezone Identifiers, like "America/Edmonton", moment-timezone can use to predict DST transitions and ensure that the times are correct.
