### ISSUE TITLE
incorporate a google calendar invite to players after a scheduling post

### ISSUE THREAD

**Issue by angborxley** [endrawes0/Chesster#53]
i'm not sure how hard this would be, but assuming we have everyone's email this might be a very nice feature - i thank cal invites could even be used by people that don't have a gmail address - but i'm not sure about that

one risk might be exposing league member's emails, maybe there's a way around that... 

to build on this, if chesster had a public calendar he could be included on the invites - then we'd have an easily viewable calendar of games.

just spit-ballin ideas - i missed my round 8 game because i messed up my own calendar entry...

**Comment by lakinwecker** [comment]
Generating an iCal feed is actually fairly straightforward. 

Also, https://github.com/endrawes0/Chesster/issues/44 might help.  It's a request to remind you for a given players games. This might also help with missing a game due to incorrect scheduling.

I don't think I want to make a google calendar, but an iCal feed wouldn't be ridiculous.  We could even make the iCal feed filter based on a playername.

So you could subscribe to specific players, rather than everyone.

**Comment by lakinwecker** [comment]
We are going to implement reminders at set times before you scheduled time for your games. Probably notify you via lichess/slack.  Would that solve this issue?

**Comment by lakinwecker** [comment]
There is an ical feed on the website now. This is superfluous.
